apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopify-apigateway-deployemnt
spec:
  # Number of pods to create
  replicas: 1 
  selector:
    matchLabels:
      app: shopify-node-app
  template:
    metadata:
      labels:
        app: shopify-node-app
    spec:
      containers:
      - name: api-gateway-container
        image: apigateway:latest
        ports:
        - containerPort: 5000

  # - name: user-service-container
  #   image: userservice:latest 
  #   ports:
  #   - containerPort: 5001
  # - name: product-service-container
  #   image: productservice:latest 
  #   ports:
  #   - containerPort: 5002
  # - name: inventory-service-container
  #   image: inventoryservice:latest 
  #   ports:
  #   - containerPort: 5003
  # - name: cart-service-container
  #   image: cartservice:latest 
  #   ports:
  #   - containerPort: 5004
  # - name: order-service-container
  #   image: orderservice:latest 
  #   ports:
  #   - containerPort: 5005

# kubectl apply -f deployment.yaml        
