apiVersion: v1
kind: Pod
metadata:
  name: shopify-app-pod
  labels:
    app: shopify-app
spec:
  containers:
  - name: api-gateway-container
    image: naguws2004/apigateway:latest
    ports:
    - containerPort: 5000
  - name: user-service-container
    image: naguws2004/userservice:latest 
    ports:
    - containerPort: 5001
  - name: product-service-container
    image: naguws2004/productservice:latest 
    ports:
    - containerPort: 5002
  - name: inventory-service-container
    image: naguws2004/inventoryservice:latest 
    ports:
    - containerPort: 5003
  - name: cart-service-container
    image: naguws2004/cartservice:latest 
    ports:
    - containerPort: 5004
  - name: order-service-container
    image: naguws2004/orderservice:latest 
    ports:
    - containerPort: 5005

# docker tag apigateway naguws2004/apigateway:latest
# docker push naguws2004/apigateway:latest
# docker tag userservice naguws2004/userservice:latest
# docker push naguws2004/userservice:latest
# docker tag productservice naguws2004/productservice:latest
# docker push naguws2004/productservice:latest
# docker tag inventoryservice naguws2004/inventoryservice:latest
# docker push naguws2004/inventoryservice:latest
# docker tag cartservice naguws2004/cartservice:latest
# docker push naguws2004/cartservice:latest
# docker tag orderservice naguws2004/orderservice:latest
# docker push naguws2004/orderservice:latest

# kubectl apply -f deployment.yaml        
# kubectl port-forward shopify-app-pod 5000:5000 5001:5001 5002:5002 5003:5003 5004:5004 5005:5005

# docker run -p 5000:5000 naguws2004/apigateway:latest
# docker run -p 5001:5001 naguws2004/userservice:latest
# docker run -p 5002:5002 naguws2004/productservice:latest
# docker run -p 5003:5003 naguws2004/inventoryservice:latest
# docker run -p 5004:5004 naguws2004/cartservice:latest
# docker run -p 5005:5005 naguws2004/orderservice:latest