apiVersion: v1
kind: Service
metadata:
  name: shopify-app-service
spec:
  selector:
    app: shopify-app
  type: NodePort 
  ports:
  - name: "api-gateway" 
    protocol: TCP
    port: 5000
    targetPort: 5000 
  - name: "user-service" 
    protocol: TCP
    port: 5001
    targetPort: 5001 
  - name: "product-service" 
    protocol: TCP
    port: 5002
    targetPort: 5002 
  - name: "inventory-service" 
    protocol: TCP
    port: 5003
    targetPort: 5003 
  - name: "cart-service" 
    protocol: TCP
    port: 5004
    targetPort: 5004 
  - name: "order-service" 
    protocol: TCP
    port: 5005
    targetPort: 5005 

# kubectl apply -f service.yaml    
